#!/bin/bash
#
# _____________________________________________________________________________________________________________________________
#                 __                                   .__        __   
#   _____ _____  |  | __ ____        ______ ___________|__|______/  |_ 
#  /     \\__  \ |  |/ // __ \      /  ___// ___\_  __ \  \____ \   __\
# |  Y Y  \/ __ \|    <\  ___/      \___ \\  \___|  | \/  |  |_> >  |  
# |__|_|  (____  /__|_ \\___  >____/____  >\___  >__|  |__|   __/|__|  
#       \/     \/     \/    \/_____/    \/     \/         |__|         
# _____________________________________________________________________________________________________________________________
#
# __________________________________________________________________
#   Title- make_script
#   MakeDate- 10/19/17
#   Script by MannyB [JetLife]
#   Info- creates bash script at ~/Desktop, change name of template, chmod +x, and opens in vim.
#       Copies boilerplate_bash.sh
# __________________________________________________________________
version="1.0"                   
#                               v.1.0 - make date
#
# __________________________________________________________________
#    _____________   ___  ______
#   / __/_  __/ _ | / _ \/_  __/
#  _\ \  / / / __ |/ , _/ / /   
# /___/ /_/ /_/ |_/_/|_| /_/    
# ___________________________________________________________________
#
###

# VARIABLES
scriptdir="$HOME/.local/bin/binrepo/0_templates"
testdir="$HOME/.local/bin/binrepo/test"
boilerplate="boilerplate_bash.sh"
read -p 'New script name: ' makescript
###
function boilerplate() {
    cd "$HOME/Desktop"
    cp "${scriptdir}"/"${boilerplate}" "${testdir}"/"${makescript}"
    sudo chmod +x "${makescript}"
}
# Open new template
vim "${testdir}"/"${makescript}"